<a href="https://colab.research.google.com/github/LauraJDiaz/Ciencia-De-Datos/blob/main/Prte12_mayo_LosSantos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_excel("/content/drive/MyDrive/censo.xlsx")
df

Mounted at /content/drive

,cod_dpto,Departamento,cod_mpio,Municipio,fec_paquete,num_paquete,num_ficha,ide_ficha_origen,ide_edificacion,ver_estructura,...,ide_Ug,persug,Capital,marca,estado,Linea_p,replicacion,fec_actualizacion_cns,C,Clasificacion
0,68,SANTANDER,68418,LOS SANTOS,2023-05-03 17:09:24.893,1687,128326,6.841800e+19,0,50118082017,...,6.841868e+26,3,0,0,0,10781693454,0,2023-11-27 10:33:13.363,4.35,A02
1,68,SANTANDER,68418,LOS SANTOS,2023-05-03 17:09:24.893,1687,128326,6.841800e+19,0,50118082017,...,6.841868e+26,5,0,0,0,10781693454,0,2023-11-27 10:33:13.363,4.95,C02
2,68,SANTANDER,68418,LOS SANTOS,2023-05-03 17:09:24.893,1687,128326,6.841800e+19,0,50118082017,...,6.841868e+26,5,0,0,0,10781693454,0,2023-11-27 10:33:13.363,4.95,C02
3,68,SANTANDER,68418,LOS SANTOS,2023-05-03 17:09:24.893,1687,128326,6.841800e+19,0,50118082017,...,6.841868e+26,5,0,0,0,10781693454,0,2023-11-27 10:33:13.363,4.95,C02
4,68,SANTANDER,68418,LOS SANTOS,2023-05-03 17:09:24.893,1687,128326,6.841800e+19,0,50118082017,...,6.841868e+26,5,0,0,0,10781693454,0,2023-11-27 10:33:13.363,4.95,C02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12982,68,SANTANDER,68418,LOS SANTOS,2023-12-06 17:24:40.143,1833,143332,6.841801e+19,0,50118082017,...,6.841868e+26,2,0,0,0,10781693454,1,2023-12-06 20:11:20.607,0.60,A05
12983,68,SANTANDER,68418,LOS SANTOS,2023-12-06 17:24:40.143,1833,143332,6.841801e+19,0,50118082017,...,6.841868e+26,2,0,0,0,10781693454,1,2023-12-06 20:11:20.607,0.60,A05
12984,68,SANTANDER,68418,LOS SANTOS,2023-12-06 17:24:40.143,1833,143330,6.841801e+19,0,50118082017,...,6.841868e+26,3,0,0,0,10781693454,1,2023-12-06 20:11:18.260,3.30,A02
12985,68,SANTANDER,68418,LOS SANTOS,2023-12-06 17:24:40.143,1833,143330,6.841801e+19,0,50118082017,...,6.841868e+26,3,0,10,91,10781693454,1,2023-12-06 20:11:18.260,3.30,A02
12986,68,SANTANDER,68418,LOS SANTOS,2023-12-06 17:24:40.143,1833,143330,6.841801e+19,0,50118082017,...,6.841868e+26,3,0,0,0,10781693454,1,2023-12-06 20:11:18.260,3.30,A02

#Columnas a Eliminar#

In [ ]:
def contar(df,feature):
  return df[feature].value_counts()

In [ ]:
for i in range(len(df.columns)):
  print(df.columns[i])
  print(contar(df,df.columns[i]))

cod_dpto
cod_dpto
68    12987
Name: count, dtype: int64
Departamento
Departamento
SANTANDER    12987
Name: count, dtype: int64
cod_mpio
cod_mpio
68418    12987
Name: count, dtype: int64
Municipio
Municipio
LOS SANTOS    12987
Name: count, dtype: int64
fec_paquete
fec_paquete
2023-05-05 17:02:21.163    175
2022-04-07 16:59:58.747    173
2023-04-27 17:15:26.073    110
2023-06-14 17:14:31.410    102
2021-06-04 07:49:31.273    101
                          ...
2019-09-18 14:04:11.723      1
2022-08-19 13:58:04.660      1
2020-03-06 07:42:16.540      1
2022-09-15 11:04:24.503      1
2023-06-05 17:45:27.880      1
Name: count, Length: 540, dtype: int64
num_paquete
num_paquete
1691    175
1420    173
1681    110
1731    102
1276    101
       ...
1020      1
1521      1
1121      1
1541      1
1721      1
Name: count, Length: 540, dtype: int64
num_ficha
num_ficha
132645    15
131487    13
143259    13
124744    13
143294    12
          ..
141146     1
140109     1
140111     1
140104     1
139084     1
Name: count, Length: 3906, dtype: int64
ide_ficha_origen
ide_ficha_origen
6.841801e+19    3242
6.841801e+19    1702
6.841800e+19    1555
6.841801e+19    1366
6.841801e+19    1323
6.841800e+19    1255
6.841800e+19    1121
6.841800e+19     721
6.841800e+19     369
6.841801e+19     155
6.841800e+19     108
6.841800e+19      42
6.841801e+19      27
6.841801e+19       1
Name: count, dtype: int64
ide_edificacion
ide_edificacion
0     6329
1     5777
3       91
2       91
4       76
6       71
5       62
15      47
17      47
12      42
8       41
9       40
11      39
13      37
10      37
7       34
14      28
18      25
19      23
16      21
25      11
23       8
20       6
22       4
Name: count, dtype: int64
ver_estructura
ver_estructura
50118082017         5413
40018082017         4478
40118082017         1926
30118082017         1056
18082017              51
30018082017           50
401L18082017           9
5.0.0 - 18082017       4
Name: count, dtype: int64
ori_encuesta
ori_encuesta
1    12987
Name: count, dtype: int64
Cod_clase
Cod_clase
3    11039
1     1760
2      188
Name: count, dtype: int64
Cod_centro_poblado
Cod_centro_poblado
0    12799
6      188
Name: count, dtype: int64
Cod_area_coordinacion
Cod_area_coordinacion
1      6592
2      4635
101    1760
Name: count, dtype: int64
Cod_area_operativa
Cod_area_operativa
10001     4884
20012     1866
101001    1760
20014     1100
20007      700
20006      684
20011      416
20010      321
20013      301
20005      261
1001       188
20009      170
20008      129
20003      114
20004       88
20002        5
Name: count, dtype: int64
Cod_uni_cobertura
Cod_uni_cobertura
990071    355
990009    328
990012    224
990477    200
990929    197
         ...
991382      1
991310      1
991146      1
991069      1
991287      1
Name: count, Length: 659, dtype: int64
Cod_comuna
Cod_comuna
99    12987
Name: count, dtype: int64
Cod_corregimiento
Cod_corregimiento
0     12127
99      709
1        99
2        52
Name: count, dtype: int64
NOM_CORREGIMIENTO
NOM_CORREGIMIENTO
SIN CORREGIMIENTO    12127
CORREGIMIENTO_S4       709
SAN MIGUEL              99
MAJADAL                 52
Name: count, dtype: int64
Cod_vereda
Cod_vereda
0      1842
3      1681
6      1584
2       681
24      586
7       536
18      517
13      481
28      469
8       392
14      302
21      301
23      263
20      258
1       250
32      247
25      247
26      239
22      238
27      233
15      214
5       199
4       161
30      133
31      124
19      120
17      119
9       115
999     101
11      100
12       80
33       78
16       49
29       42
10        5
Name: count, dtype: int64
NOM_VEREDA
NOM_VEREDA
SIN VEREDA         1842
TABACAL            1681
LA FUENTE          1584
EL VERDE            681
ESPINAL ALTO        586
ROSABLANCA          536
LAGUNA BAJA         517
EL POZO             481
LA PURNIA           469
DELICIAS            392
GARBANZAL           302
EL GUAMITO          301
REGADERO BAJO       263
MAJADAL ALTO        262
PASOCHICO           258
EL CARRIZAL         250
PIEDRA DEL RAYO     247
ESPINAL BAJO        247
EL POTRERO          239
REGADERO ALTO       238
LAS LLANADAS        233
LOS TERES           214
MAJADAL BAJO        199
PURNIA NUEVA        133
LOMA DE PURNIA      124
LA LOMA             120
LAGUNA ALTA         119
SAN RAFAEL          115
LA MOJARRA          100
LA PEÑA              80
GUAIMARO             78
EL DIAMANTE          49
PURNIA CHIQUITA      42
SALAZAR               5
Name: count, dtype: int64
Cod_barrio
Cod_barrio
0    11389
9      407
6      229
7      171
3      156
2      141
4      135
5      131
1      115
8      113
Name: count, dtype: int64
NOM_BARRIO
NOM_BARRIO
BARRIO_S4           11389
SAN MARTIN            407
LOS GUANES            229
MIRAFLORES            171
LA ESPERANZA          156
CHIQUINQUIRA          141
LA MILAGROSA          135
LAS NIEVES            131
ALTAMIRA              115
PERPETUO SOCORRO      113
Name: count, dtype: int64
Cod_enumerador
Cod_enumerador
5292    5068
5296    1398
5295    1231
7301    1107
5297    1049
5294    1021
5298    1010
5301     564
5299     464
5300      75
Name: count, dtype: int64
tot_viviendas
tot_viviendas
0    12987
Name: count, dtype: int64
tot_hogares
tot_hogares
1    10031
2     2156
3      669
4       89
5       42
Name: count, dtype: int64
ord_vivienda
ord_vivienda
1    12893
2       90
4        4
Name: count, dtype: int64
ind_direccion
ind_direccion
2    12459
1      528
Name: count, dtype: int64
Dir_vivienda
Dir_vivienda
VEREDA LA FUENTE ALTOS DE LA FUENTE                   104
BARRIO SAN MARTIN                                      87
VEREDA TABACAL                                         60
VEREDA LA FUENTE ALTOS DE LOS MANTILLA                 56
VEREDA MAJADAL ALTO                                    52
                                                     ...
VEREDA LA FUENTE (LINDEROS)                             1
VEREDA EL VERDE (SEC LOS URIBE LA MANCHA)               1
CL 3 # 10 - 13                                          1
VEREDA REGADERO BAJO FC EL PINAL                        1
VEREDA LA LAGUNA FC MI FORTUNA ( CERCA A LA BOMBA)      1
Name: count, Length: 3090, dtype: int64
uso_vivienda
uso_vivienda
1    12987
Name: count, dtype: int64
Ide_foto
Ide_foto
Fachada68418004529500000222.jpg    15
Fachada68418004529500000168.jpg    13
Fachada68418004529500000253.jpg    13
Fachada68418003529900000061.jpg    13
Fachada68418008529700000192.jpg    13
                                   ..
Fachada68418014529100009571.jpg     1
Fachada68418014529100009570.jpg     1
Fachada68418014529100009568.jpg     1
Fachada68418014529100009563.jpg     1
Fachada68418014529100009546.jpg     1
Name: count, Length: 3902, dtype: int64
fec_ini_encuesta
fec_ini_encuesta
2020-11-05 14:03:53.000    15
2019-06-27 09:01:55.000    13
2019-07-08 11:17:22.000    13
2019-07-03 18:58:55.000    13
2023-05-12 12:05:04.000    12
                           ..
2023-09-25 16:51:49.000     1
2023-09-14 09:45:34.000     1
2023-09-14 10:34:00.000     1
2023-09-14 07:41:13.000     1
2023-09-08 10:59:41.000     1
Name: count, Length: 3906, dtype: int64
fec_fin_encuesta
fec_fin_encuesta
2023-06-01 11:01:48.000    15
2022-11-21 17:12:15.000    13
2023-05-12 14:56:55.000    13
2023-11-03 16:05:36.000    13
2023-12-19 16:29:13.000    12
                           ..
2023-09-14 09:50:08.000     1
2023-09-14 10:45:45.000     1
2023-09-14 07:47:23.000     1
2023-09-08 11:03:48.000     1
2022-09-21 16:39:03.000     1
Name: count, Length: 3907, dtype: int64
Coord_x_manual_rec
Coord_x_manual_rec
676784500    18
675608300    16
680301300    16
684394100    16
680116000    16
             ..
677799900     1
687143400     1
679544900     1
679567800     1
675477000     1
Name: count, Length: 3448, dtype: int64
Coord_y_manual_rec
Coord_y_manual_rec
-7309995800    22
-7310171500    20
-7310266100    19
-7309890700    18
-7310273700    17
               ..
-7308016200     1
-7310359800     1
-7310254000     1
-7310293300     1
-7308125800     1
Name: count, Length: 3399, dtype: int64
Coord_x_auto_rec
Coord_x_auto_rec
687389029    15
682775626    13
686330390    13
675660333    13
681541251    13
             ..
682023599     1
677529818     1
677844884     1
682554282     1
679589304     1
Name: count, Length: 3902, dtype: int64
Coord_y_auto_rec
Coord_y_auto_rec
-7310306295    15
-7310157365    13
-7311215229    13
-7310295157    13
-7313426958    13
               ..
-7316014697     1
-7316225142     1
-7313271482     1
-7312932957     1
-7310055554     1
Name: count, Length: 3901, dtype: int64
Gps_Alt_auto_rec
Gps_Alt_auto_rec
1675    91
1671    87
1681    86
1691    86
1695    83
        ..
1607     1
1475     1
1774     1
1542     1
1148     1
Name: count, Length: 795, dtype: int64
Fec_captura_gps_rec
Fec_captura_gps_rec
2020-11-05 14:03:18.000    15
2019-06-04 17:01:22.000    13
2019-06-27 09:01:11.000    13
2019-07-08 11:17:13.000    13
2019-07-03 18:58:25.000    13
                           ..
2023-11-08 15:35:44.000     1
2023-12-05 12:25:19.000     1
2023-12-05 12:42:38.000     1
2023-11-02 15:26:42.000     1
2023-10-24 11:11:49.000     1
Name: count, Length: 3902, dtype: int64
Gps_Distancia_rec
Gps_Distancia_rec
49       218
54       207
51       204
57       189
53       184
        ...
501        1
203        1
374        1
11911      1
7485       1
Name: count, Length: 606, dtype: int64
Coord_x_manual_enc
Coord_x_manual_enc
676784500    18
684394100    16
680116000    16
681914200    16
680301300    16
             ..
675874700     1
688115900     1
675565200     1
686311500     1
687851800     1
Name: count, Length: 3443, dtype: int64
Coord_y_manual_enc
Coord_y_manual_enc
-7309995800    22
-7310250100    21
-7309890700    18
-7310387400    17
-7310273700    17
               ..
-7314619400     1
-7310134500     1
-7310135400     1
-7309723300     1
-7308016200     1
Name: count, Length: 3405, dtype: int64
Coord_x_auto_enc
Coord_x_auto_enc
687389029    15
682775626    13
681541251    13
686330390    13
675716558    12
             ..
675605900     1
686326703     1
687892440     1
687200725     1
683565053     1
Name: count, Length: 3906, dtype: int64
Coord_y_auto_enc
Coord_y_auto_enc
-7310306295    15
-7313426958    13
-7311215229    13
-7310295157    13
-7308766923    12
               ..
-7309871513     1
-7309752217     1
-7308210853     1
-7308033860     1
-7310437859     1
Name: count, Length: 3907, dtype: int64
Gps_Alt_auto_enc
Gps_Alt_auto_enc
1675    91
1671    87
1681    86
1691    86
1690    83
        ..
1131     1
1542     1
1774     1
1481     1
1382     1
Name: count, Length: 797, dtype: int64
Fec_captura_gps_enc
Fec_captura_gps_enc
Jul  2 2019 11:57AM    20
Nov  5 2020  2:03PM    15
Jun 12 2019  8:00AM    14
Jul  8 2019 11:17AM    13
Jun 27 2019  9:01AM    13
                       ..
Sep 14 2023  7:40AM     1
Nov  2 2023  3:06PM     1
Oct 10 2023 11:59AM     1
Oct 10 2023  9:52AM     1
2019-06-12 11:27:43     1
Name: count, Length: 3863, dtype: int64
Gps_Distancia_enc
Gps_Distancia_enc
0       1187
54       191
49       191
51       190
57       177
        ...
651        1
962        1
1057       1
1179       1
2831       1
Name: count, Length: 598, dtype: int64
Est_nov_cartografia
Est_nov_cartografia
0    11800
1     1187
Name: count, dtype: int64
Cod_digitador
Cod_digitador
5292    5068
5296    1398
5295    1231
7301    1107
5297    1049
5294    1021
5298    1010
5301     564
5299     464
5300      75
Name: count, dtype: int64
Fec_digitacion
Fec_digitacion
2020-11-05 14:03:53.000    15
2019-06-27 09:01:55.000    13
2019-07-08 11:17:22.000    13
2019-07-03 18:58:55.000    13
2023-05-12 12:05:04.000    12
                           ..
2023-09-14 10:34:00.000     1
2023-09-14 07:41:13.000     1
2023-09-08 10:59:41.000     1
2023-11-02 15:26:59.000     1
2023-10-24 11:12:15.000     1
Name: count, Length: 3905, dtype: int64
ind_formato
ind_formato
2    12069
1      918
Name: count, dtype: int64
Num_hogares_recuento
Num_hogares_recuento
1    10031
2     2156
3      669
4       89
5       42
Name: count, dtype: int64
est_ficha
est_ficha
1    12987
Name: count, dtype: int64
Cod_equipo_encuesta
Cod_equipo_encuesta
7    5851
8    2548
6    1398
4    1231
1    1010
3     949
Name: count, dtype: int64
Num_visita
Num_visita
2    8202
1    4785
Name: count, dtype: int64
Cod_Chip
Series([], Name: count, dtype: int64)
Dir_Chip
Series([], Name: count, dtype: int64)
Num_solicitud
Num_solicitud
0         988
301983     15
344313     13
259322     13
297881     13
         ...
338258      1
337249      1
330233      1
330225      1
330224      1
Name: count, Length: 3540, dtype: int64
Cod_UC_total
Cod_UC_total
1.706842e+33    11039
1.706842e+33     1760
1.706842e+33      188
Name: count, dtype: int64
tip_vivienda
tip_vivienda
1    9795
3    3157
4      20
2      13
5       2
Name: count, dtype: int64
tip_mat_paredes
tip_mat_paredes
1    8313
2    4028
3     324
7     107
5      92
6      79
4      44
Name: count, dtype: int64
tip_mat_pisos
tip_mat_pisos
3    7877
2    3120
5    1949
4      27
6      14
Name: count, dtype: int64
ind_tiene_energia
ind_tiene_energia
1    12594
2      393
Name: count, dtype: int64
tip_estrato_energia
tip_estrato_energia
1     6382
2     5961
99     393
3      156
0       95
Name: count, dtype: int64
ind_tiene_alcantarillado
ind_tiene_alcantarillado
2    11617
1     1370
Name: count, dtype: int64
ind_tiene_gas
ind_tiene_gas
2    12256
1      731
Name: count, dtype: int64
ind_tiene_recoleccion
ind_tiene_recoleccion
2    7140
1    5847
Name: count, dtype: int64
ind_tiene_acueducto
ind_tiene_acueducto
2    11542
1     1445
Name: count, dtype: int64
tip_estrato_acueducto
tip_estrato_acueducto
99    11542
2       918
1       480
3        39
0         8
Name: count, dtype: int64
num_cuartos_vivienda
num_cuartos_vivienda
2    4160
1    3814
3    3153
4    1439
5     321
6      84
7      16
Name: count, dtype: int64
num_hogares_vivienda
num_hogares_vivienda
1    10137
2     2097
3      637
4       80
5       36
Name: count, dtype: int64
cod_encuestador
cod_encuestador
5292    5068
5296    1371
5295    1267
7301    1107
5294    1040
5298    1037
5297    1020
5301     564
5299     346
5300     167
Name: count, dtype: int64
cod_supervisor
cod_supervisor
8301    5966
5292    3678
5293    3343
Name: count, dtype: int64
cod_critico
cod_critico
9999    12987
Name: count, dtype: int64
fec_ini_vivienda
fec_ini_vivienda
2020-11-05 14:03:53.000    15
2019-06-27 09:01:55.000    13
2019-07-08 11:17:23.000    13
2019-07-03 18:58:55.000    13
2023-05-12 12:05:04.000    12
                           ..
2023-09-25 16:51:49.000     1
2023-09-14 09:45:34.000     1
2023-09-14 10:34:00.000     1
2023-09-14 07:41:14.000     1
2023-09-08 10:59:41.000     1
Name: count, Length: 3906, dtype: int64
fec_fin_vivienda
fec_fin_vivienda
2023-06-01 11:01:48.000    15
2022-11-21 17:12:15.000    13
2023-05-12 14:56:55.000    13
2023-11-03 16:05:36.000    13
2023-12-19 16:29:13.000    12
                           ..
2023-09-14 09:50:08.000     1
2023-09-14 10:45:45.000     1
2023-09-14 07:47:23.000     1
2023-09-08 11:03:48.000     1
2022-09-21 16:39:03.000     1
Name: count, Length: 3907, dtype: int64
ide_hogar
ide_hogar
1    11571
2     1168
3      214
4       27
5        7
Name: count, dtype: int64
tip_ocupa_vivienda
tip_ocupa_vivienda
1    6321
4    4928
3    1222
2     283
5     233
Name: count, dtype: int64
num_cuartos_exclusivos
num_cuartos_exclusivos
1    6379
2    3820
3    1965
4     413
0     333
5      68
6       9
Name: count, dtype: int64
num_cuartos_dormir
num_cuartos_dormir
1    8657
2    3172
3     709
0     391
4      51
5       7
Name: count, dtype: int64
num_cuartos_unicos_dormir
num_cuartos_unicos_dormir
1    8583
2    3102
3     677
0     567
4      51
5       7
Name: count, dtype: int64
tip_sanitario
tip_sanitario
2    8546
5    2042
1    1149
3    1031
4     219
Name: count, dtype: int64
tip_ubi_sanitario
tip_ubi_sanitario
2    6340
1    4605
9    2042
Name: count, dtype: int64
tip_uso_sanitario
tip_uso_sanitario
1    7381
2    2559
9    2042
3    1005
Name: count, dtype: int64
tip_origen_agua
tip_origen_agua
5    5383
4    3585
2    1410
1    1294
7     825
6     375
3      73
9      42
Name: count, dtype: int64
ind_agua_llega_7dias
ind_agua_llega_7dias
9    11693
1     1201
2       93
Name: count, dtype: int64
num_dias_llega
num_dias_llega
9    12895
3       41
4       21
2       11
5       10
6        9
Name: count, dtype: int64
ind_agua_llega_24horas
ind_agua_llega_24horas
9    11693
2      845
1      449
Name: count, dtype: int64
num_horas_llega
num_horas_llega
99    12142
6       296
5       111
8       100
4        92
0        62
7        47
3        38
10       38
2        34
12       15
16        4
20        4
1         4
Name: count, dtype: int64
tip_uso_agua_beber
tip_uso_agua_beber
1    9680
2    2528
3     457
4     204
6     116
5       2
Name: count, dtype: int64
tip_elimina_basura
tip_elimina_basura
1    5535
3    3567
2    2657
6     719
7     328
4     181
Name: count, dtype: int64
ind_tiene_cocina
ind_tiene_cocina
1    10635
2     2352
Name: count, dtype: int64
tip_prepara_alimentos
tip_prepara_alimentos
1    7516
4    3433
3    1667
5     351
2      20
Name: count, dtype: int64
tip_uso_cocina
tip_uso_cocina
1    9394
2    2742
3     578
9     273
Name: count, dtype: int64
tip_energia_cocina
tip_energia_cocina
6    7335
3    4835
2     426
9     273
7      84
1      18
4      16
Name: count, dtype: int64
ind_tiene_nevera
ind_tiene_nevera
1    7406
2    5581
Name: count, dtype: int64
ind_tiene_lavadora
ind_tiene_lavadora
2    11912
1     1075
Name: count, dtype: int64
ind_tiene_pc
ind_tiene_pc
2    12833
1      154
Name: count, dtype: int64
ind_tiene_internet
ind_tiene_internet
2    12802
1      185
Name: count, dtype: int64
ind_tiene_moto
ind_tiene_moto
2    11458
1     1529
Name: count, dtype: int64
ind_tiene_tractor
ind_tiene_tractor
2    12966
1       21
Name: count, dtype: int64
ind_tiene_carro
ind_tiene_carro
2    12741
1      246
Name: count, dtype: int64
ind_tiene_bien_raiz
ind_tiene_bien_raiz
2    12469
1      518
Name: count, dtype: int64
ind_gasto_alimento
ind_gasto_alimento
1    12623
9      234
2      130
Name: count, dtype: int64
vlr_gasto_alimento
vlr_gasto_alimento
200000     2821
300000     2611
400000     1404
150000     1186
250000     1069
           ...
175000        1
55000         1
260000        1
255000        1
2000000       1
Name: count, Length: 66, dtype: int64
ind_gasto_transporte
ind_gasto_transporte
2    9659
1    3246
9      82
Name: count, dtype: int64
vlr_gasto_transporte
vlr_gasto_transporte
0         9741
50000      614
100000     454
20000      439
30000      333
40000      287
60000      228
80000      176
200000     137
150000      97
10000       84
120000      58
15000       57
70000       35
300000      35
90000       30
25000       27
24000       19
12000       15
180000      12
500000      10
400000       9
5000         8
250000       7
35000        6
11000        6
130000       6
75000        6
160000       5
240000       5
84000        4
110000       4
22000        4
16000        4
45000        4
8000         3
105000       3
230000       3
350000       3
164000       2
7000         2
18000        1
32000        1
6000         1
64000        1
56000        1
Name: count, dtype: int64
ind_gasto_educacion
ind_gasto_educacion
2    10274
1     2633
9       80
Name: count, dtype: int64
vlr_gasto_educacion
vlr_gasto_educacion
0          10354
50000        361
100000       317
40000        262
80000        251
30000        241
60000        227
20000        175
200000       110
150000        99
120000        92
35000         59
70000         58
10000         50
300000        36
400000        22
160000        22
15000         21
25000         16
500000        14
250000        14
140000         9
36000          9
90000          9
45000          8
32000          8
650000         8

*Se eliminan las columnas cuyo valor de conteo sea 12987*

In [ ]:
df_2 = df.drop(["Capital", "ide_Unigasto", "vlr_ingr_remesa_exterior" ,"ide_serv_domestico" , "ind_pariente_domestico", "Ind_declaracion", "cod_critico", "est_ficha", "cod_dpto" ,"Departamento" ,"cod_mpio", "Municipio", "ori_encuesta" ,"Cod_comuna" ,"tot_viviendas" ,"uso_vivienda","Cod_Chip","Dir_Chip", ], axis=1)

##Datos NAN##

In [ ]:
from tabulate import tabulate

In [ ]:
def contar_nan(df,feature):
  return df[feature].isna().sum()

tabla_nan_data=[]
for column in df_2.columns:
  nan_count = contar_nan(df_2,column)
  tabla_nan_data.append([column,nan_count])
tabla_nan_data

headers_nan=["Feature","Cantidad Nan"]
tabla_nan_data=tabulate(tabla_nan_data,headers_nan,tablefmt="fancy_grid")

print(tabla_nan_data)

╒═══════════════════════════╤════════════════╕
│ Feature                   │   Cantidad Nan │
╞═══════════════════════════╪════════════════╡
│ fec_paquete               │              0 │
├───────────────────────────┼────────────────┤
│ num_paquete               │              0 │
├───────────────────────────┼────────────────┤
│ num_ficha                 │              0 │
├───────────────────────────┼────────────────┤
│ ide_ficha_origen          │              0 │
├───────────────────────────┼────────────────┤
│ ide_edificacion           │              0 │
├───────────────────────────┼────────────────┤
│ ver_estructura            │              0 │
├───────────────────────────┼────────────────┤
│ Cod_clase                 │              0 │
├───────────────────────────┼────────────────┤
│ Cod_centro_poblado        │              0 │
├───────────────────────────┼────────────────┤
│ Cod_area_coordinacion     │              0 │
├───────────────────────────┼────────────────┤
│ Cod_area_operativa        │              0 │
├───────────────────────────┼────────────────┤
│ Cod_uni_cobertura         │              0 │
├───────────────────────────┼────────────────┤
│ Cod_corregimiento         │              0 │
├───────────────────────────┼────────────────┤
│ NOM_CORREGIMIENTO         │              0 │
├───────────────────────────┼────────────────┤
│ Cod_vereda                │              0 │
├───────────────────────────┼────────────────┤
│ NOM_VEREDA                │              0 │
├───────────────────────────┼────────────────┤
│ Cod_barrio                │              0 │
├───────────────────────────┼────────────────┤
│ NOM_BARRIO                │              0 │
├───────────────────────────┼────────────────┤
│ Cod_enumerador            │              0 │
├───────────────────────────┼────────────────┤
│ tot_hogares               │              0 │
├───────────────────────────┼────────────────┤
│ ord_vivienda              │              0 │
├───────────────────────────┼────────────────┤
│ ind_direccion             │              0 │
├───────────────────────────┼────────────────┤
│ Dir_vivienda              │              0 │
├───────────────────────────┼────────────────┤
│ Ide_foto                  │              0 │
├───────────────────────────┼────────────────┤
│ fec_ini_encuesta          │              0 │
├───────────────────────────┼────────────────┤
│ fec_fin_encuesta          │              0 │
├───────────────────────────┼────────────────┤
│ Coord_x_manual_rec        │              0 │
├───────────────────────────┼────────────────┤
│ Coord_y_manual_rec        │              0 │
├───────────────────────────┼────────────────┤
│ Coord_x_auto_rec          │              0 │
├───────────────────────────┼────────────────┤
│ Coord_y_auto_rec          │              0 │
├───────────────────────────┼────────────────┤
│ Gps_Alt_auto_rec          │              0 │
├───────────────────────────┼────────────────┤
│ Fec_captura_gps_rec       │              0 │
├───────────────────────────┼────────────────┤
│ Gps_Distancia_rec         │              0 │
├───────────────────────────┼────────────────┤
│ Coord_x_manual_enc        │              0 │
├───────────────────────────┼────────────────┤
│ Coord_y_manual_enc        │              0 │
├───────────────────────────┼────────────────┤
│ Coord_x_auto_enc          │              0 │
├───────────────────────────┼────────────────┤
│ Coord_y_auto_enc          │              0 │
├───────────────────────────┼────────────────┤
│ Gps_Alt_auto_enc          │              0 │
├───────────────────────────┼────────────────┤
│ Fec_captura_gps_enc       │              0 │
├───────────────────────────┼────────────────┤
│ Gps_Distancia_enc         │              0 │
├───────────────────────────┼────────────────┤
│ Est_nov_cartografia       │              0 │
├───────────────────────────┼────────────────┤
│ Cod_digitador             │              0 │
├───────────────────────────┼────────────────┤
│ Fec_digitacion            │              0 │
├───────────────────────────┼────────────────┤
│ ind_formato               │              0 │
├───────────────────────────┼────────────────┤
│ Num_hogares_recuento      │              0 │
├───────────────────────────┼────────────────┤
│ Cod_equipo_encuesta       │              0 │
├───────────────────────────┼────────────────┤
│ Num_visita                │              0 │
├───────────────────────────┼────────────────┤
│ Num_solicitud             │              0 │
├───────────────────────────┼────────────────┤
│ Cod_UC_total              │              0 │
├───────────────────────────┼────────────────┤
│ tip_vivienda              │              0 │
├───────────────────────────┼────────────────┤
│ tip_mat_paredes           │              0 │
├───────────────────────────┼────────────────┤
│ tip_mat_pisos             │              0 │
├───────────────────────────┼────────────────┤
│ ind_tiene_energia         │              0 │
├───────────────────────────┼────────────────┤
│ tip_estrato_energia       │              0 │
├───────────────────────────┼────────────────┤
│ ind_tiene_alcantarillado  │              0 │
├───────────────────────────┼────────────────┤
│ ind_tiene_gas             │              0 │
├───────────────────────────┼────────────────┤
│ ind_tiene_recoleccion     │              0 │
├───────────────────────────┼────────────────┤
│ ind_tiene_acueducto       │              0 │
├───────────────────────────┼────────────────┤
│ tip_estrato_acueducto     │              0 │
├───────────────────────────┼────────────────┤
│ num_cuartos_vivienda      │              0 │
├───────────────────────────┼────────────────┤
│ num_hogares_vivienda      │              0 │
├───────────────────────────┼────────────────┤
│ cod_encuestador           │              0 │
├───────────────────────────┼────────────────┤
│ cod_supervisor            │              0 │
├───────────────────────────┼────────────────┤
│ fec_ini_vivienda          │              0 │
├───────────────────────────┼────────────────┤
│ fec_fin_vivienda          │              0 │
├───────────────────────────┼────────────────┤
│ ide_hogar                 │              0 │
├───────────────────────────┼────────────────┤
│ tip_ocupa_vivienda        │              0 │
├───────────────────────────┼────────────────┤
│ num_cuartos_exclusivos    │              0 │
├───────────────────────────┼────────────────┤
│ num_cuartos_dormir        │              0 │
├───────────────────────────┼────────────────┤
│ num_cuartos_unicos_dormir │              0 │
├───────────────────────────┼────────────────┤
│ tip_sanitario             │              0 │
├───────────────────────────┼────────────────┤
│ tip_ubi_sanitario         │              0 │
├───────────────────────────┼────────────────┤
│ tip_uso_sanitario         │              0 │
├───────────────────────────┼────────────────┤
│ tip_origen_agua           │              0 │
├───────────────────────────┼────────────────┤
│ ind_agua_llega_7dias      │              0 │
├───────────────────────────┼────────────────┤
│ num_dias_llega            │              0 │
├───────────────────────────┼────────────────┤
│ ind_agua_llega_24horas    │              0 │
├───────────────────────────┼────────────────┤
│ num_horas_llega           │              0 │
├───────────────────────────┼────────────────┤
│ tip_uso_agua_beber        │              0 │
├───────────────────────────┼────────────────┤
│ tip_elimina_basura        │              0 │
├───────────────────────────┼────────────────┤
│ ind_tiene_cocina          │              0 │
├───────────────────────────┼────────────────┤
│ tip_prepara_alimentos     │              0 │
├───────────────────────────┼────────────────┤
│ tip_uso_cocina            │              0 │
├───────────────────────────┼────────────────┤
│ tip_energia_cocina        │              0 │
├───────────────────────────┼────────────────┤
│ ind_tiene_nevera          │              0 │
├───────────────────────────┼────────────────┤
│ ind_tiene_lavadora        │              0 │
├───────────────────────────┼────────────────┤
│ ind_tiene_pc              │              0 │
├───────────────────────────┼────────────────┤
│ ind_tiene_internet        │              0 │
├───────────────────────────┼────────────────┤
│ ind_tiene_moto            │              0 │
├───────────────────────────┼────────────────┤
│ ind_tiene_tractor         │              0 │
├───────────────────────────┼────────────────┤
│ ind_tiene_carro           │              0 │
├───────────────────────────┼────────────────┤
│ ind_tiene_bien_raiz       │              0 │
├───────────────────────────┼────────────────┤
│ ind_gasto_alimento        │              0 │
├───────────────────────────┼────────────────┤
│ vlr_gasto_alimento        │              0 │
├───────────────────────────┼────────────────┤
│ ind_gasto_transporte      │              0 │
├───────────────────────────┼────────────────┤
│ vlr_gasto_transporte      │              0 │
├───────────────────────────┼────────────────┤
│ ind_gasto_educacion       │              0 │
├───────────────────────────┼────────────────┤
│ vlr_gasto_educacion       │              0 │
├───────────────────────────┼────────────────┤
│ ind_gasto_salud           │              0 │
├───────────────────────────┼────────────────┤
│ vlr_gasto_salud           │              0 │
├───────────────────────────┼────────────────┤
│ ind_gasto_serv_publicos   │              0 │
├───────────────────────────┼────────────────┤
│ vlr_gasto_serv_publicos   │              0 │
├───────────────────────────┼────────────────┤
│ ind_gasto_celular         │              0 │
├───────────────────────────┼────────────────┤
│ vlr_gasto_celular         │              0 │
├───────────────────────────┼────────────────┤
│ ind_gasto_arriendo        │              0 │
├───────────────────────────┼────────────────┤
│ vlr_gasto_arriendo        │              0 │
├───────────────────────────┼────────────────┤
│ ind_gasto_otros           │              0 │
├───────────────────────────┼────────────────┤
│ vlr_gasto_otros           │              0 │
├───────────────────────────┼────────────────┤
│ vlr_total_gastos          │              0 │
├───────────────────────────┼────────────────┤
│ num_habita_vivienda       │              0 │
├───────────────────────────┼────────────────┤
│ ind_evento_inundacion     │              0 │
├───────────────────────────┼────────────────┤
│ num_evento_inundacion     │              0 │
├───────────────────────────┼────────────────┤
│ ind_evento_avalancha      │              0 │
├───────────────────────────┼────────────────┤
│ num_evento_avalancha      │              0 │
├───────────────────────────┼────────────────┤
│ ind_evento_terremoto      │              0 │
├───────────────────────────┼────────────────┤
│ num_evento_terremoto      │              0 │
├───────────────────────────┼────────────────┤
│ ind_evento_incendio       │              0 │
├───────────────────────────┼────────────────┤
│ num_evento_incendio       │              0 │
├───────────────────────────┼────────────────┤
│ ind_evento_vendaval       │              0 │
├───────────────────────────┼────────────────┤
│ num_evento_vendaval       │              0 │
├───────────────────────────┼────────────────┤
│ ind_evento_hundimiento    │              0 │
├───────────────────────────┼────────────────┤
│ num_evento_hundimiento    │              0 │
├───────────────────────────┼────────────────┤
│ num_personas_posibles     │              0 │
├───────────────────────────┼────────────────┤
│ num_personas_hogar        │              0 │
├───────────────────────────┼────────────────┤
│ fec_ini_visita1           │            693 │
├───────────────────────────┼────────────────┤
│ fec_fin_visita1           │            693 │
├───────────────────────────┼────────────────┤
│ res_visita1               │              0 │
├───────────────────────────┼────────────────┤
│ fec_ini_visita2           │           6311 │
├───────────────────────────┼────────────────┤
│ fec_fin_visita2           │           1181 │
├───────────────────────────┼────────────────┤
│ res_visita2               │              0 │
├───────────────────────────┼────────────────┤
│ ide_informante            │              0 │
├───────────────────────────┼────────────────┤
│ pri_nom_informante        │              0 │
├───────────────────────────┼────────────────┤
│ seg_nom_informante        │           6176 │
├───────────────────────────┼────────────────┤
│ pri_ape_informante        │              0 │
├───────────────────────────┼────────────────┤
│ seg_ape_informante        │            394 │
├───────────────────────────┼────────────────┤
│ Tip_informante            │              0 │
├───────────────────────────┼────────────────┤
│ ide_firma_informante      │            140 │
├───────────────────────────┼────────────────┤
│ Cau_sin_firma             │              0 │
├───────────────────────────┼────────────────┤
│ Email_contacto            │          12772 │
├───────────────────────────┼────────────────┤
│ num_tel_contacto          │              0 │
├───────────────────────────┼────────────────┤
│ ide_persona               │              0 │
├───────────────────────────┼────────────────┤
│ ide_nacional              │              0 │
├───────────────────────────┼────────────────┤
│ ind_escaner               │              0 │
├───────────────────────────┼────────────────┤
│ pri_apellido              │              0 │
├───────────────────────────┼────────────────┤
│ seg_apellido              │            254 │
├───────────────────────────┼────────────────┤
│ pri_nombre                │              0 │
├───────────────────────────┼────────────────┤
│ seg_nombre                │           4849 │
├───────────────────────────┼────────────────┤
│ sexo_persona              │              0 │
├───────────────────────────┼────────────────┤
│ ori_persona               │              0 │
├───────────────────────────┼────────────────┤
│ tip_documento             │              0 │
├───────────────────────────┼────────────────┤
│ Num_documento             │              0 │
├───────────────────────────┼────────────────┤
│ fec_nacimiento            │              0 │
├───────────────────────────┼────────────────┤
│ edad_calculada            │              0 │
├───────────────────────────┼────────────────┤
│ cod_dpto_documento        │              0 │
├───────────────────────────┼────────────────┤
│ cod_mpio_documento        │              0 │
├───────────────────────────┼────────────────┤
│ Cod_pais_documento        │              0 │
├───────────────────────────┼────────────────┤
│ tip_parentesco            │              0 │
├───────────────────────────┼────────────────┤
│ tip_estado_civil          │              0 │
├───────────────────────────┼────────────────┤
│ ind_conyuge_vive_hogar    │              0 │
├───────────────────────────┼────────────────┤
│ ide_conyuge               │              0 │
├───────────────────────────┼────────────────┤
│ ind_padre_vive_hogar      │              0 │
├───────────────────────────┼────────────────┤
│ ide_padre                 │              0 │
├───────────────────────────┼────────────────┤
│ ind_discap_ver            │              0 │
├───────────────────────────┼────────────────┤
│ ind_discap_oir            │              0 │
├───────────────────────────┼────────────────┤
│ ind_discap_hablar         │              0 │
├───────────────────────────┼────────────────┤
│ ind_discap_moverse        │              0 │
├───────────────────────────┼────────────────┤
│ ind_discap_bañarse        │              0 │
├───────────────────────────┼────────────────┤
│ ind_discap_salir          │              0 │
├───────────────────────────┼────────────────┤
│ ind_discap_entender       │              0 │
├───────────────────────────┼────────────────┤
│ ind_discap_ninguna        │              0 │
├───────────────────────────┼────────────────┤
│ tip_seg_social            │              0 │
├───────────────────────────┼────────────────┤
│ ind_enfermo_30            │              0 │
├───────────────────────────┼────────────────┤
│ ind_acudio_salud          │              0 │
├───────────────────────────┼────────────────┤
│ ind_fue_atendido_salud    │              0 │
├───────────────────────────┼────────────────┤
│ ind_esta_embarazada       │              0 │
├───────────────────────────┼────────────────┤
│ ind_tuvo_hijos            │              0 │
├───────────────────────────┼────────────────┤
│ tip_cuidado_niños         │              0 │
├───────────────────────────┼────────────────┤
│ ind_recibe_comida         │              0 │
├───────────────────────────┼────────────────┤
│ ind_leer_escribir         │              0 │
├───────────────────────────┼────────────────┤
│ ind_estudia               │              0 │
├───────────────────────────┼────────────────┤
│ niv_educativo             │              0 │
├───────────────────────────┼────────────────┤
│ grado_alcanzado           │              0 │
├───────────────────────────┼────────────────┤
│ ind_fondo_pensiones       │              0 │
├───────────────────────────┼────────────────┤
│ tip_actividad_mes         │              0 │
├───────────────────────────┼────────────────┤
│ num_sem_buscando          │              0 │
├───────────────────────────┼────────────────┤
│ tip_empleado              │              0 │
├───────────────────────────┼────────────────┤
│ ind_ingr_salario          │              0 │
├───────────────────────────┼────────────────┤
│ vlr_ingr_salario          │              0 │
├───────────────────────────┼────────────────┤
│ ind_ingr_honorarios       │              0 │
├───────────────────────────┼────────────────┤
│ vlr_ingr_honorarios       │              0 │
├───────────────────────────┼────────────────┤
│ ind_ingr_cosecha          │              0 │
├───────────────────────────┼────────────────┤
│ num_mes_ingr_cosecha      │              0 │
├───────────────────────────┼────────────────┤
│ vlr_ingr_cosecha          │              0 │
├───────────────────────────┼────────────────┤
│ ind_ingr_pension          │              0 │
├───────────────────────────┼────────────────┤
│ vlr_ingr_pension          │              0 │
├───────────────────────────┼────────────────┤
│ ind_ingr_remesa_pais      │              0 │
├───────────────────────────┼────────────────┤
│ vlr_ingr_remesa_pais      │              0 │
├───────────────────────────┼────────────────┤
│ ind_ingr_remesa_exterior  │              0 │
├───────────────────────────┼────────────────┤
│ ind_ingr_arriendos        │              0 │
├───────────────────────────┼────────────────┤
│ vlr_ingr_arriendos        │              0 │
├───────────────────────────┼────────────────┤
│ ind_otros_ingresos        │              0 │
├───────────────────────────┼────────────────┤
│ vlr_otros_ingresos        │              0 │
├───────────────────────────┼────────────────┤
│ ind_ingr_estado           │              0 │
├───────────────────────────┼────────────────┤
│ vlr_ingr_fam_accion       │              0 │
├───────────────────────────┼────────────────┤
│ vlr_ingr_col_mayor        │              0 │
├───────────────────────────┼────────────────┤
│ vlr_ingr_otro_subsidio    │              0 │
├───────────────────────────┼────────────────┤
│ fec_ini_persona1          │           6221 │
├───────────────────────────┼────────────────┤
│ fec_fin_persona1          │           6220 │
├───────────────────────────┼────────────────┤
│ fec_ini_persona2          │              0 │
├───────────────────────────┼────────────────┤
│ fec_fin_persona2          │              0 │
├───────────────────────────┼────────────────┤
│ Jefe_UG                   │           8476 │
├───────────────────────────┼────────────────┤
│ H_5                       │              0 │
├───────────────────────────┼────────────────┤

*Limpieza de los datos NAN*

In [ ]:
# Convertir a datetime
df_2['fec_ini_visita2'] = pd.to_datetime(df_2['fec_ini_visita2'], errors='coerce')
df_2['fec_fin_visita2'] = pd.to_datetime(df_2['fec_fin_visita2'], errors='coerce')


## FECHAS DE VISITA ##

#En la visita 1 habian 693 datos tanto en el inc como en el fin

df_2['visita1_realizada'] = df_2['fec_ini_visita1'].notna().astype(int)

#En la visita 2 habian mas datos NAN en la fecha de inc
df_2['visita2_realizada'] = df_2[['fec_ini_visita2', 'fec_fin_visita2']].notna().any(axis=1).astype(int)
df_2['fec_ini_visita2'] = df_2['fec_ini_visita2'].fillna(df_2['fec_fin_visita2'])

In [ ]:
## DATOS PERSONALES ##

df_2['seg_nom_informante'] = df_2['seg_nom_informante'].fillna('NO TIENE')
df_2['seg_ape_informante'] = df_2['seg_ape_informante'].fillna('NO TIENE')

df_2['seg_apellido'] = df_2['seg_apellido'].fillna('NO TIENE')
df_2['seg_nombre'] = df_2['seg_nombre'].fillna('NO TIENE')

In [ ]:
## FIRMA DEL INFROMANTE ##

df_2['informante_firmo'] = df_2['ide_firma_informante'].notna().astype(int)
df_2['ide_firma_informante'] = df_2['ide_firma_informante'].fillna('NO FIRMÓ')

In [ ]:
## EMAIL ##

df_2['tiene_email'] = df_2['Email_contacto'].notna().astype(int)
df_2['Email_contacto'] = df_2['Email_contacto'].fillna('NO TIENE CORREO')

In [ ]:
## JEFE UG##

df_2['jefe_ug_identificado'] = df_2['Jefe_UG'].apply(lambda x: 1 if x == 1 else 0)

In [ ]:
## ACTUALIZACION CNS ##
df_2['cns_actualizado'] = df_2['fec_actualizacion_cns'].notna().astype(int)
df_2['fec_actualizacion_cns'] = df_2['fec_actualizacion_cns'].fillna('NO ACTUALIZADO')

In [ ]:
## PERSONA 1  ##
df_2['persona1_encuestada'] = df_2['fec_ini_persona1'].notna().astype(int)

In [ ]:
df_2[['visita1_realizada', 'visita2_realizada', 'informante_firmo', 'tiene_email', 'cns_actualizado']].head(15)

,visita1_realizada,visita2_realizada,informante_firmo,tiene_email,cns_actualizado
0,1,1,1,0,1
1,1,1,1,0,1
2,1,1,1,0,1
3,1,1,1,0,1
4,1,1,1,0,1
5,1,1,1,0,1
6,1,1,1,0,1
7,1,1,1,0,1
8,1,0,1,0,1
9,1,0,1,0,1
10,1,0,1,0,1
11,1,0,1,0,1
12,1,0,1,0,1
13,1,1,1,0,1
14,1,0,1,0,1

In [ ]:
df_2.columns[df_2.isna().any()]

Index(['fec_ini_visita1', 'fec_fin_visita1', 'fec_ini_visita2',
       'fec_fin_visita2', 'fec_ini_persona1', 'fec_fin_persona1', 'Jefe_UG'],
      dtype='object')

#Parte 2 Analisis de Clusters#

In [ ]:
df_2.columns

Index(['fec_paquete', 'num_paquete', 'num_ficha', 'ide_ficha_origen',
       'ide_edificacion', 'ver_estructura', 'Cod_clase', 'Cod_centro_poblado',
       'Cod_area_coordinacion', 'Cod_area_operativa',
       ...
       'fec_actualizacion_cns', 'C', 'Clasificacion', 'visita1_realizada',
       'visita2_realizada', 'informante_firmo', 'tiene_email',
       'jefe_ug_identificado', 'cns_actualizado', 'persona1_encuestada'],
      dtype='object', length=244)

In [ ]:
variables_funcionales = [
    'ind_ingr_cosecha', 'ind_ingr_salario', 'ind_ingr_estado',
    'ind_ingr_honorarios', 'ind_ingr_pension', 'ind_fondo_pensiones',
    'C', 'edad_calculada', 'tip_empleado'
]


df_cluster = df_2[variables_funcionales].copy()
df_cluster = pd.get_dummies(df_cluster, columns=['tip_empleado'], prefix='empleo')

df_cluster.columns.tolist()

['ind_ingr_cosecha',
 'ind_ingr_salario',
 'ind_ingr_estado',
 'ind_ingr_honorarios',
 'ind_ingr_pension',
 'ind_fondo_pensiones',
 'C',
 'edad_calculada',
 'empleo_1',
 'empleo_2',
 'empleo_3',
 'empleo_4',
 'empleo_5',
 'empleo_6',
 'empleo_7',
 'empleo_8',
 'empleo_9',
 'empleo_10',
 'empleo_99']

| Código | Ocupación                                                        | Zona asignada            | Justificación                                                                |
| ------ | ---------------------------------------------------------------- | ------------------------ | ---------------------------------------------------------------------------- |
| 1      | Empleado de empresa particular                                   | Urbana                   | Trabajo asalariado no rural, alta probabilidad de estar en ciudad.           |
| 2      | Empleado del gobierno                                            | Urbana                   | Claramente urbano, en sector público.                                        |
| 3      | Empleado doméstico                                               | Urbana                   | Actividad asociada a hogares urbanos.                                        |
| 4      | Profesional independiente                                        | Urbana                   | Generalmente ubicado en zona urbana.                                         |
| 5      | Trabajador independiente o por cuenta propia                     | Urbana                   | Puede ser mixto, pero lo inferimos como urbano por descarte.                 |
| 6      | Patrón o empleador                                               | **Avícola**              | Lo inferimos como productor avícola en ausencia de ingresos agrícolas.       |
| 7      | Trabajador de finca, tierra o parcela propia                     | Agrícola                 | Trabajo directamente ligado a actividades agrícolas.                         |
| 8      | Trabajador sin remuneración                                      | **Avícola**              | Lo inferimos como ayudante o trabajador familiar en finca avícola.           |
| 9      | Ayudante sin remuneración (hijo o familiar de empleados rurales) | **Avícola**              | Similar al 8, se infiere que apoya labores productivas rurales no agrícolas. |
| 10     | Jornalero o peón                                                 | Agrícola                 | Típicamente vinculado a labores agrícolas.                                   |
| 99     | No aplica                                                        | NaN (o "Sin clasificar") | No hay forma de inferir.                                                     |

In [ ]:
UMBRAL_URBANO = df['vlr_ingr_salario'].quantile(0.75)

In [ ]:
UMBRALMEDIO_URBANO = df['vlr_ingr_salario'].quantile(0.5)

In [ ]:
def asignar_zona(row):
    salario = row['vlr_ingr_salario']
    ingr_agricola = row['vlr_ingr_cosecha']
    emp = row['tip_empleado']

    # 1. Agrícola
    if ingr_agricola > 0 or emp in [7, 10]:
        return 'Agrícola'

    # 2. Urbana
    if emp in [2, 4, 5]:  # Ajusta el umbral a lo que consideres alto
        return 'Urbana'

    # 3. Mineral
    if emp == 1 and salario > UMBRAL_URBANO:
        return 'Mineral'

    # 4. Avícola
    if emp in [6, 8, 9]:
        return 'Avícola'

    # 5. No clasificados
    return np.nan

# Aplicar al DataFrame
df['zona_final'] = df.apply(asignar_zona, axis=1)

In [ ]:
print(df['zona_final'].value_counts())

zona_final
Agrícola    1350
Urbana       582
Mineral      401
Avícola       31
Name: count, dtype: int64

In [ ]:
import pandas as pd
from tabulate import tabulate  # opcional para imprimir bonito en consola

# Función para construir el perfil por zona con tus variables corregidas
def construir_perfil(df):
    perfil = df.groupby('zona_final').agg(
        Total=('zona_final', 'count'),
        Edad_Promedio=('edad_calculada', 'mean'),
        Porc_Mujeres=('sexo_persona', lambda x: (x == 2).mean() * 100),
        Porc_Educ_Baja=('niv_educativo', lambda x: (x.isin([0, 1, 2])).mean() * 100),
        Porc_Pobreza_Multidimensional=('C', lambda x: (x > 5).mean() * 100),
        Salario_Promedio=('vlr_ingr_salario', 'mean')
    ).round(2)

    # Formatear columnas para presentación
    perfil['Edad_Promedio'] = perfil['Edad_Promedio'].astype(int)
    perfil['Salario_Promedio'] = perfil['Salario_Promedio'].apply(lambda x: f"${x:,.0f}")
    perfil['Porc_Mujeres'] = perfil['Porc_Mujeres'].astype(str) + "%"
    perfil['Porc_Educ_Baja'] = perfil['Porc_Educ_Baja'].astype(str) + "%"
    perfil['Porc_Pobreza_Multidimensional'] = perfil['Porc_Pobreza_Multidimensional'].astype(str) + "%"

    return perfil

# Ejecutar función
tabla_perfil = construir_perfil(df)

# Mostrar bonito en Jupyter
display(tabla_perfil)

# Mostrar bonito en consola
print(tabulate(tabla_perfil, headers='keys', tablefmt='fancy_grid'))

,Total,Edad_Promedio,Porc_Mujeres,Porc_Educ_Baja,Porc_Pobreza_Multidimensional,Salario_Promedio
zona_final,,,,,,
Agrícola,1350,41,14.89%,64.0%,23.85%,"$192,702"
Avícola,31,36,54.84%,58.06%,35.48%,$0
Mineral,401,39,18.7%,46.38%,5.49%,"$596,313"
Urbana,582,41,34.36%,44.85%,15.64%,"$74,739"

╒══════════════╤═════════╤═════════════════╤════════════════╤══════════════════╤═════════════════════════════════╤════════════════════╕
│ zona_final   │   Total │   Edad_Promedio │ Porc_Mujeres   │ Porc_Educ_Baja   │ Porc_Pobreza_Multidimensional   │ Salario_Promedio   │
╞══════════════╪═════════╪═════════════════╪════════════════╪══════════════════╪═════════════════════════════════╪════════════════════╡
│ Agrícola     │    1350 │              41 │ 14.89%         │ 64.0%            │ 23.85%                          │ $192,702           │
├──────────────┼─────────┼─────────────────┼────────────────┼──────────────────┼─────────────────────────────────┼────────────────────┤
│ Avícola      │      31 │              36 │ 54.84%         │ 58.06%           │ 35.48%                          │ $0                 │
├──────────────┼─────────┼─────────────────┼────────────────┼──────────────────┼─────────────────────────────────┼────────────────────┤
│ Mineral      │     401 │              39 │ 18.7%          │ 46.38%           │ 5.49%                           │ $596,313           │
├──────────────┼─────────┼─────────────────┼────────────────┼──────────────────┼─────────────────────────────────┼────────────────────┤
│ Urbana       │     582 │              41 │ 34.36%         │ 44.85%           │ 15.64%                          │ $74,739            │
╘══════════════╧═════════╧═════════════════╧════════════════╧══════════════════╧═════════════════════════════════╧════════════════════╛